site_name: NGINX Learning Path
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
  font:
    text: Roboto
    code: Roboto Mono

use_directory_urls: false
docs_dir: docs

nav:
  - Home: index.md
  - Go to Production: production.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - tags

extra:
  generator: false