site_name: NGINX Learning Path
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
  font:
    text: Roboto
    code: Roboto Mono

use_directory_urls: false
docs_dir: docs

nav:
  - Home: index.md
  - Go to Production: production.md
  - Foundational Concepts:
      - NGINX Configuration: foundational/configuration.md
      - NGINX .conf File: foundational/nginx_conf.md
      - Creating a Virtual Host: foundational/virtual_host.md
      - NGINX Location Contents: foundational/location_contents.md
      - NGINX Variables: foundational/variables.md
      - NGINX Rewrites and Returns: foundational/rewrites_returns.md
      - NGINX Try Files: foundational/try_files.md
      - NGINX Logs: foundational/logs.md
      - NGINX Inherentance and directives: foundational/inheritance_directives.md
      - PHP Processing: foundational/php_processing.md
      - NGINX Worker Processes: foundational/worker_processes.md
      - NGINX Buffers and Timeouts: foundational/buffers_timeouts.md
      - NGINX Modules: foundational/modules.md
  - Performance:
  - Security:
  - Load Balancing:

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - tags

extra:
  generator: false