site_name: Software Development Learning Path
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs

use_directory_urls: false
docs_dir: docs

nav:
  - NGINX:
    - index.md
    - Go to Production: production.md
    - Foundational Concepts: foundational.md
    - Performance: performance.md
    - Security: security.md
    - Load Balancing: load_balancing.md
  - uv:
    - uv/index.md
    - Quickstart: uv/quickstart.md
  - DMS SQL CDC:
    - dms-aws/index.md
    - DMS Source: dms-aws/dms-source.md
    - DMS Target: dms-aws/dms-target.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - tags

extra:
  generator: false