site_name: Software Development Learning Path
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs

use_directory_urls: false
docs_dir: docs

nav:
  - NGINX:
    - index.md
    - Go to Production: production.md
    - Foundational Concepts: foundational.md
    - Performance: performance.md
    - Security: security.md
    - Load Balancing: load_balancing.md
  - uv:
    - uv/index.md
    - Quickstart: uv/quickstart.md
  - DMS SQL CDC:
    - dms-aws/index.md
    - DMS Source: dms-aws/dms-source.md
    - DMS Target: dms-aws/dms-target.md
  - Bash Scripting:
    - bash_scripting/index.md
    - Introduction: bash_scripting/introduction.md
    - Commands: bash_scripting/commands.md
  - Assembly Language:
    - assembly_language/index.md
  - Amazon Q:
    - amazon_q/index.md
    - Getting Started: amazon_q/getting_started.md
    - Creating a Bot: amazon_q/creating_a_bot.md
    - Advanced Features: amazon_q/advanced_features.md
  - Test Python CDK code:
    - test_python_cdk_code/index.md
    - Unit Testing: test_python_cdk_code/unit_testing.md
    - Integration Testing: test_python_cdk_code/integration_testing.md
  - AWS Nag:
    - aws_nag/index.md
    - Setup and Installation: aws_nag/setup_and_installation.md
    - Usage: aws_nag/usage.md
    - Best Practices: aws_nag/best_practices.md
  - AWS SNS:
    - aws_sns/index.md
    - Getting Started: aws_sns/getting_started.md
    - Publishing Messages: aws_sns/publishing_messages.md
    - Subscribing to Topics: aws_sns/subscribing_to_topics.md
    - Troubleshooting: aws_sns/troubleshooting.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - tags

extra:
  generator: false